### ISSUE TITLE
BUG: error thrown from ClassDeclaration

### ISSUE THREAD

**Issue by nazimjamil** [lm-a/gen-flow-files#4]
Issue: When generating .flow.js files the build fails with the following error: `TypeError: Property name expected type of string but got null`

Steps to reproduce:

1. Try to run `gen-flow-files` on a Class structured like this:
```
type ResponseObject = {
  body: mixed,
  callback: () => void,
  error: string,
  statusCode: number,
};

class RandomUtil {
    static RandomUtilReturn({ body, callback, error, statusCode } : ResponseObject) {
...
```
Expected Result:
* A randomUtil.flow.js file

Actual Result:
* An error
* No files generated

Additional:
* It only happens when a method in the class is using an object spread in the arguments.

Environment:
macOS 10.14.2
node v8.11.3
yarn v1.5.1
flow-bin v^0.94.0
gen-flow-files v^0.4.3

**Comment by ilyalesik** [comment]
Thanks for the issue. I fixed it at `0.4.4`. 
`static RandomUtilReturn({ body, callback, error, statusCode } : ResponseObject)` will be converted to `static RandomUtilReturn(arg0 : ResponseObject)` because object spreading in the arguments is not supported at declarations: [repl](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AJSwM4awB2BWA8gEYBWWAxiqALygDeioXoVsAJmgBcoALYBLAB5Y+AGk7d6AQ2jQqi+gGthACgCULAHygAbrDGz5XLACdrsa8IIprYkgHM53UE8UoArgQAwvxYwiR+IlQ2cgC+ANzIfAzQitY49CkEBHiKJHywIgCqKGLQ7JY5eQXFpfj+1iTabLwCMqBKKmqabTZ21m0+-kEhMcL4RKTk1HSMusK5aAkxQA).
